### ISSUE TITLE
No muestra las coordenadas

### ISSUE THREAD

**Issue by nmassi** [guidoferreyra/showCoordinates#1]
En la consola del macro no tira nada. Instalé los módulos desde Preferencias.

![screen shot 2016-04-30 at 2 47 06 pm](https://cloud.githubusercontent.com/assets/374627/14937717/647489f2-0ee6-11e6-8c6f-549647893f5c.png)

![screen shot 2016-04-30 at 3 13 44 pm](https://cloud.githubusercontent.com/assets/374627/14937714/545ba6f4-0ee6-11e6-8b26-111ad0b1bca1.png)
![screen shot 2016-04-30 at 3 13 24 pm](https://cloud.githubusercontent.com/assets/374627/14937715/545c3af6-0ee6-11e6-914a-97a3e2394a3d.png)

**Comment by guidoferreyra** [comment]
Tengo la misma version beta y el error no aparece.

Seguro que la consola de Window > Macro Panel no arroja nada? Por lo general siempre que algo no funciona se ve reflejado allí.

Con los módulos me refería a los que aparecen en la ventana de preferencias > addons > pestaña módulos. Los tienes instalados seguro?

Saludos.

**Comment by nmassi** [comment]
En macro no, nada. Los módulos, asumo que están aunque en la ventana no muestra nada... al darle install me pide sudo y algo hace :P

![screen shot 2016-04-30 at 3 27 22 pm](https://cloud.githubusercontent.com/assets/374627/14937779/4a830b02-0ee8-11e6-8e96-3f202880d695.png)

**Comment by nmassi** [comment]
https://forum.glyphsapp.com/t/install-modules/3432/4

**Comment by guidoferreyra** [comment]
Sí, los reinstala, pero sigue sin funcionar no? Descartado eso entonces.

Proba abrir la app de OSX Consola y en el campo de búsqueda tipeá Glyphs, a ver que aparece. 
Algo que se me ocurre es que a veces cuando alguna otra extensión está en conflicto frena a las demás. Así que veamos que sale en el log de la Consola.

**Comment by nmassi** [comment]
![screen shot 2016-04-30 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/374627/14937866/618eb132-0eea-11e6-9f01-167671c669d1.png)

**Comment by guidoferreyra** [comment]
Podrías abrir y mostrarme uno de los mensajes de Show Coordinates desde el triángulo gris de la izquierda?

**Comment by nmassi** [comment]
![screen shot 2016-04-30 at 3 47 23 pm](https://cloud.githubusercontent.com/assets/374627/14937893/df8bcaac-0eea-11e6-93a4-1cb102e38059.png)

**Comment by guidoferreyra** [comment]
Modifique unas líneas en el código, probá descargando e instalando de nuevo.

**Comment by nmassi** [comment]
Sigue igual. Borré el anterior, instale de nuevo. En la consola osx sigue estando el mismo error

**Comment by guidoferreyra** [comment]
Hmm voy a tener que con mas tiempo y en detalle y probablemente consultar por ahi. Te aviso cuando tenga novedades. Saludos.

**Comment by nmassi** [comment]
No hay problema Guido, gracias!

**Comment by nmassi** [comment]
Hice File > New, y al dibujar algo aparecieron las coordenadas! Estaba probando con un archivo preexistente :) Espero que con ese dato puedas corregir el problema. Saludos

**Comment by guidoferreyra** [comment]
bueno ahora si que es mas extraño jaja. Si no te molesta me podrías enviar una copia de ese archivo a guidoferreyra89@gmail.com Hay una extension de mekkablue que se llama [Disguiser](https://github.com/mekkablue/Disguiser) para reemplazar las formas por rectángulos por si queres que no se vean la formas de los glifos. Si no todo bien :)

**Comment by nmassi** [comment]
jaja, que extensión esa!... No sólo me pasa con ese archivo. Podes probar lo siguiente, file new y pegá alguna forma de otro archivo .glyph y tampoco muestra las coordenadas.

**Comment by guidoferreyra** [comment]
El tema es que no puedo reproducir el error. Copio y pego de otros archivos, abro archivos viejos, creo nuevos y siempre veo las coordenadas.
