### ISSUE TITLE
Can you fix this?

### ISSUE THREAD

**Issue by franciscotorress** [guidoferreyra/showCoordinates#2]
It works, but I get this message every time I open glyphs. Can you fix it?

<img width="532" alt="captura de ecra 2018-05-30 as 17 42 46" src="https://user-images.githubusercontent.com/38395134/40734689-1211d8d4-6431-11e8-9878-4dafe6533e27.png">

**Comment by guidoferreyra** [comment]
Just updated to the new codebase for Glyphs 2.5. Update or reinstall via plugin manager.
Cheers.
